version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: task-manager-db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=task-manager
    ports:
      - "5435:5432"